// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: follower/proto/follower.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_follower_proto_follower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_follower_proto_follower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_follower_proto_follower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_follower_proto_follower_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RecommendationsResponse struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	Recommendations []*RecommendationsResponse_RecUser `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendationsResponse) Reset() {
	*x = RecommendationsResponse{}
	mi := &file_follower_proto_follower_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsResponse) ProtoMessage() {}

func (x *RecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsResponse.ProtoReflect.Descriptor instead.
func (*RecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendationsResponse) GetRecommendations() []*RecommendationsResponse_RecUser {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_follower_proto_follower_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{5}
}

func (x *StatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowersCount int64                  `protobuf:"varint,2,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount int64                  `protobuf:"varint,3,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_follower_proto_follower_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{6}
}

func (x *StatsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StatsResponse) GetFollowersCount() int64 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *StatsResponse) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_follower_proto_follower_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{7}
}

func (x *GetListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListResponse) Reset() {
	*x = GetListResponse{}
	mi := &file_follower_proto_follower_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListResponse) ProtoMessage() {}

func (x *GetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListResponse.ProtoReflect.Descriptor instead.
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{8}
}

func (x *GetListResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type IsFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_follower_proto_follower_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{9}
}

func (x *IsFollowingRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *IsFollowingRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type IsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResponse) Reset() {
	*x = IsFollowingResponse{}
	mi := &file_follower_proto_follower_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResponse) ProtoMessage() {}

func (x *IsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResponse.ProtoReflect.Descriptor instead.
func (*IsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{10}
}

func (x *IsFollowingResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type RecommendationsResponse_RecUser struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MutualConnections int64                  `protobuf:"varint,2,opt,name=mutual_connections,json=mutualConnections,proto3" json:"mutual_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecommendationsResponse_RecUser) Reset() {
	*x = RecommendationsResponse_RecUser{}
	mi := &file_follower_proto_follower_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsResponse_RecUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsResponse_RecUser) ProtoMessage() {}

func (x *RecommendationsResponse_RecUser) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_follower_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsResponse_RecUser.ProtoReflect.Descriptor instead.
func (*RecommendationsResponse_RecUser) Descriptor() ([]byte, []int) {
	return file_follower_proto_follower_proto_rawDescGZIP(), []int{4, 0}
}

func (x *RecommendationsResponse_RecUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationsResponse_RecUser) GetMutualConnections() int64 {
	if x != nil {
		return x.MutualConnections
	}
	return 0
}

var File_follower_proto_follower_proto protoreflect.FileDescriptor

const file_follower_proto_follower_proto_rawDesc = "" +
	"\n" +
	"\x1dfollower/proto/follower.proto\x12\bfollower\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\rFollowRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"(\n" +
	"\x0eFollowResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\".\n" +
	"\x0fUnfollowRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"*\n" +
	"\x10UnfollowResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc1\x01\n" +
	"\x17RecommendationsResponse\x12S\n" +
	"\x0frecommendations\x18\x01 \x03(\v2).follower.RecommendationsResponse.RecUserR\x0frecommendations\x1aQ\n" +
	"\aRecUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x12mutual_connections\x18\x02 \x01(\x03R\x11mutualConnections\"'\n" +
	"\fStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"z\n" +
	"\rStatsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ffollowers_count\x18\x02 \x01(\x03R\x0efollowersCount\x12'\n" +
	"\x0ffollowing_count\x18\x03 \x01(\x03R\x0efollowingCount\")\n" +
	"\x0eGetListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x0fGetListResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"V\n" +
	"\x12IsFollowingRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\"8\n" +
	"\x13IsFollowingResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing2\x88\x06\n" +
	"\x0fFollowerService\x12Z\n" +
	"\x06Follow\x12\x17.follower.FollowRequest\x1a\x18.follower.FollowResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/social/follow\x12b\n" +
	"\bUnfollow\x12\x19.follower.UnfollowRequest\x1a\x1a.follower.UnfollowResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/social/unfollow\x12t\n" +
	"\x12GetRecommendations\x12\x16.google.protobuf.Empty\x1a!.follower.RecommendationsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/social/recommendations\x12f\n" +
	"\bGetStats\x12\x16.follower.StatsRequest\x1a\x17.follower.StatsResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/social/users/{user_id}/stats\x12r\n" +
	"\fGetFollowers\x12\x18.follower.GetListRequest\x1a\x19.follower.GetListResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/social/users/{user_id}/followers\x12r\n" +
	"\fGetFollowing\x12\x18.follower.GetListRequest\x1a\x19.follower.GetListResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/social/users/{user_id}/following\x12o\n" +
	"\vIsFollowing\x12\x1c.follower.IsFollowingRequest\x1a\x1d.follower.IsFollowingResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/social/is-followingB Z\x1ePROJEKAT/COMMON/follower/protob\x06proto3"

var (
	file_follower_proto_follower_proto_rawDescOnce sync.Once
	file_follower_proto_follower_proto_rawDescData []byte
)

func file_follower_proto_follower_proto_rawDescGZIP() []byte {
	file_follower_proto_follower_proto_rawDescOnce.Do(func() {
		file_follower_proto_follower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follower_proto_follower_proto_rawDesc), len(file_follower_proto_follower_proto_rawDesc)))
	})
	return file_follower_proto_follower_proto_rawDescData
}

var file_follower_proto_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_follower_proto_follower_proto_goTypes = []any{
	(*FollowRequest)(nil),                   // 0: follower.FollowRequest
	(*FollowResponse)(nil),                  // 1: follower.FollowResponse
	(*UnfollowRequest)(nil),                 // 2: follower.UnfollowRequest
	(*UnfollowResponse)(nil),                // 3: follower.UnfollowResponse
	(*RecommendationsResponse)(nil),         // 4: follower.RecommendationsResponse
	(*StatsRequest)(nil),                    // 5: follower.StatsRequest
	(*StatsResponse)(nil),                   // 6: follower.StatsResponse
	(*GetListRequest)(nil),                  // 7: follower.GetListRequest
	(*GetListResponse)(nil),                 // 8: follower.GetListResponse
	(*IsFollowingRequest)(nil),              // 9: follower.IsFollowingRequest
	(*IsFollowingResponse)(nil),             // 10: follower.IsFollowingResponse
	(*RecommendationsResponse_RecUser)(nil), // 11: follower.RecommendationsResponse.RecUser
	(*emptypb.Empty)(nil),                   // 12: google.protobuf.Empty
}
var file_follower_proto_follower_proto_depIdxs = []int32{
	11, // 0: follower.RecommendationsResponse.recommendations:type_name -> follower.RecommendationsResponse.RecUser
	0,  // 1: follower.FollowerService.Follow:input_type -> follower.FollowRequest
	2,  // 2: follower.FollowerService.Unfollow:input_type -> follower.UnfollowRequest
	12, // 3: follower.FollowerService.GetRecommendations:input_type -> google.protobuf.Empty
	5,  // 4: follower.FollowerService.GetStats:input_type -> follower.StatsRequest
	7,  // 5: follower.FollowerService.GetFollowers:input_type -> follower.GetListRequest
	7,  // 6: follower.FollowerService.GetFollowing:input_type -> follower.GetListRequest
	9,  // 7: follower.FollowerService.IsFollowing:input_type -> follower.IsFollowingRequest
	1,  // 8: follower.FollowerService.Follow:output_type -> follower.FollowResponse
	3,  // 9: follower.FollowerService.Unfollow:output_type -> follower.UnfollowResponse
	4,  // 10: follower.FollowerService.GetRecommendations:output_type -> follower.RecommendationsResponse
	6,  // 11: follower.FollowerService.GetStats:output_type -> follower.StatsResponse
	8,  // 12: follower.FollowerService.GetFollowers:output_type -> follower.GetListResponse
	8,  // 13: follower.FollowerService.GetFollowing:output_type -> follower.GetListResponse
	10, // 14: follower.FollowerService.IsFollowing:output_type -> follower.IsFollowingResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_follower_proto_follower_proto_init() }
func file_follower_proto_follower_proto_init() {
	if File_follower_proto_follower_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follower_proto_follower_proto_rawDesc), len(file_follower_proto_follower_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follower_proto_follower_proto_goTypes,
		DependencyIndexes: file_follower_proto_follower_proto_depIdxs,
		MessageInfos:      file_follower_proto_follower_proto_msgTypes,
	}.Build()
	File_follower_proto_follower_proto = out.File
	file_follower_proto_follower_proto_goTypes = nil
	file_follower_proto_follower_proto_depIdxs = nil
}
