services:
  # --- BAZA ZA STAKEHOLDERS ---
  stakeholders-db:
    image: postgres:15
    container_name: stakeholders-db
    environment:
      POSTGRES_DB: stakeholders
      POSTGRES_USER: stakeholders
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stakeholders"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- API GATEWAY ---
  gateway:
    build: 
      context: .
      dockerfile: API_GATEWAY/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - stakeholders
      - blog
      - auth
      - follower

  # --- AUTH SERVIS ---
  auth:
    build: 
      context: .
      dockerfile: AUTH/Dockerfile
    container_name: auth
    ports:
      - "8082:8082"
    environment:
      DB_HOST: auth-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth
      DB_PORT: 5432
    depends_on:
      auth-db:
        condition: service_healthy # <--- OVO JE KLJUCNA IZMENA (Ceka da baza pozeleni)

  # --- BAZA ZA AUTH ---
  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    # --- OVO JE DODATO ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- STAKEHOLDERS SERVIS ---
  stakeholders:
    build: 
      context: .
      dockerfile: STAKEHOLDERS/Dockerfile
    container_name: stakeholders
    environment:
      DATABASE_URL: host=stakeholders-db user=stakeholders password=secretpassword dbname=stakeholders port=5432 sslmode=disable
    depends_on:
      stakeholders-db:
        condition: service_healthy
    ports:
      - "8081:8081"
      - "50051:50051"
    
  # --- BLOG SERVIS ---
  blog:
    build: 
      context: .
      dockerfile: BLOG/Dockerfile
    container_name: blog
    ports:
      - "5251:5251"
      - "9091:9091"
    volumes:
      - ./BLOG:/src
    environment:
      ASPNETCORE_URLS: "http://+:5251;http://+:9091"
      Kestrel__Endpoints__Grpc__Url: "http://*:9091"
      Kestrel__Endpoints__Grpc__Protocols: "Http2"
      
      MongoDatabaseSettings__ConnectionString: "mongodb://blog-db:27017"
      MongoDatabaseSettings__DatabaseName: "BlogDB"
    depends_on:
      - blog-db

  # --- BAZA ZA BLOG ---
  blog-db:
    image: mongo:6
    container_name: blog-db
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: BlogDB
    volumes:
      - blog-data:/data/db
    
  tour:
    build:
      context: .
      dockerfile: TOUR/Dockerfile
    container_name: tour
    ports:
      - "8083:8083"
    environment:
      DB_HOST: tour-db
      DB_USER: tour
      DB_PASSWORD: tourpassword
      DB_NAME: tour
      DB_PORT: 5432
    depends_on:
      tour-db:
        condition: service_healthy
    volumes:
      - ./TOUR:/src

  tour-db:
    image: postgres:16
    container_name: tour-db
    restart: always
    environment:
      POSTGRES_DB: tour
      POSTGRES_USER: tour
      POSTGRES_PASSWORD: tourpassword
    ports:
      - "5434:5432"   # External 5434 → internal 5432
    volumes:
      - tour_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tour"]
      interval: 3s
      timeout: 3s
      retries: 5

  follower:
    build: 
      context: .
      dockerfile: FOLLOWER/Dockerfile
    container_name: follower
    ports:
      - 9090:9090
    environment:
      - NEO4J_URI=bolt://follower-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=secretpassword
    depends_on:
      follower-db:
        condition: service_healthy
    volumes:
      - ./FOLLOWER:/src

  follower-db:
    image: neo4j:5.26
    container_name: follower-db
    ports:
      - "7474:7474" #HTTP Browser
      - "7687:7687" #Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/secretpassword
    volumes:
      - follower_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  blog-data:
  auth_data:
  pgdata:
  tour_data:
  follower_data:
