// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: tour/proto/tour.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =========================
// ENUMS
// =========================
type RouteMode int32

const (
	RouteMode_WALKING RouteMode = 0
	RouteMode_CYCLING RouteMode = 1
	RouteMode_DRIVING RouteMode = 2
)

// Enum value maps for RouteMode.
var (
	RouteMode_name = map[int32]string{
		0: "WALKING",
		1: "CYCLING",
		2: "DRIVING",
	}
	RouteMode_value = map[string]int32{
		"WALKING": 0,
		"CYCLING": 1,
		"DRIVING": 2,
	}
)

func (x RouteMode) Enum() *RouteMode {
	p := new(RouteMode)
	*p = x
	return p
}

func (x RouteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_tour_proto_tour_proto_enumTypes[0].Descriptor()
}

func (RouteMode) Type() protoreflect.EnumType {
	return &file_tour_proto_tour_proto_enumTypes[0]
}

func (x RouteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteMode.Descriptor instead.
func (RouteMode) EnumDescriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{0}
}

type TourStatus int32

const (
	TourStatus_DRAFT     TourStatus = 0
	TourStatus_PUBLISHED TourStatus = 1
	TourStatus_ARCHIVED  TourStatus = 2
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "ARCHIVED",
	}
	TourStatus_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"ARCHIVED":  2,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tour_proto_tour_proto_enumTypes[1].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_tour_proto_tour_proto_enumTypes[1]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{1}
}

// =========================
// MESSAGES
// =========================
type Keypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keypoint) Reset() {
	*x = Keypoint{}
	mi := &file_tour_proto_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keypoint) ProtoMessage() {}

func (x *Keypoint) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keypoint.ProtoReflect.Descriptor instead.
func (*Keypoint) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{0}
}

func (x *Keypoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Keypoint) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *Keypoint) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Keypoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Keypoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Keypoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Keypoint) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type RouteOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Mode          RouteMode              `protobuf:"varint,3,opt,name=mode,proto3,enum=tour.RouteMode" json:"mode,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteOption) Reset() {
	*x = RouteOption{}
	mi := &file_tour_proto_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOption) ProtoMessage() {}

func (x *RouteOption) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOption.ProtoReflect.Descriptor instead.
func (*RouteOption) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{1}
}

func (x *RouteOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteOption) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *RouteOption) GetMode() RouteMode {
	if x != nil {
		return x.Mode
	}
	return RouteMode_WALKING
}

func (x *RouteOption) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          string                 `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	Status        TourStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tour.TourStatus" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Distance      float64                `protobuf:"fixed64,9,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      int64                  `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"` // in milliseconds
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	Keypoints     []*Keypoint            `protobuf:"bytes,14,rep,name=keypoints,proto3" json:"keypoints,omitempty"`
	RouteOptions  []*RouteOption         `protobuf:"bytes,15,rep,name=route_options,json=routeOptions,proto3" json:"route_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tour_proto_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{2}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Tour) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Tour) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_DRAFT
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Tour) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Tour) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tour) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Tour) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *Tour) GetKeypoints() []*Keypoint {
	if x != nil {
		return x.Keypoints
	}
	return nil
}

func (x *Tour) GetRouteOptions() []*RouteOption {
	if x != nil {
		return x.RouteOptions
	}
	return nil
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VisitedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=visited_at,json=visitedAt,proto3" json:"visited_at,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_tour_proto_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{3}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *Review) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Review) GetVisitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitedAt
	}
	return nil
}

func (x *Review) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// =========================
// REQUEST MESSAGES
// =========================
type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTourRequest) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type UpdateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourRequest) Reset() {
	*x = UpdateTourRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourRequest) ProtoMessage() {}

func (x *UpdateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTourRequest) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type GetTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourRequest) Reset() {
	*x = GetTourRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourRequest) ProtoMessage() {}

func (x *GetTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourRequest.ProtoReflect.Descriptor instead.
func (*GetTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{6}
}

func (x *GetTourRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetToursByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByUserRequest) Reset() {
	*x = GetToursByUserRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByUserRequest) ProtoMessage() {}

func (x *GetToursByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByUserRequest.ProtoReflect.Descriptor instead.
func (*GetToursByUserRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{7}
}

func (x *GetToursByUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type DeleteTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTourRequest) Reset() {
	*x = DeleteTourRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTourRequest) ProtoMessage() {}

func (x *DeleteTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTourRequest.ProtoReflect.Descriptor instead.
func (*DeleteTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTourRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{9}
}

func (x *CreateReviewRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type GetReviewsByTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByTourRequest) Reset() {
	*x = GetReviewsByTourRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByTourRequest) ProtoMessage() {}

func (x *GetReviewsByTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByTourRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsByTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{10}
}

func (x *GetReviewsByTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_tour_proto_tour_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// =========================
// RESPONSE WRAPPERS
// =========================
type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_tour_proto_tour_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{12}
}

func (x *TourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type GetAllToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursResponse) Reset() {
	*x = GetAllToursResponse{}
	mi := &file_tour_proto_tour_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursResponse) ProtoMessage() {}

func (x *GetAllToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllToursResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_tour_proto_tour_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{14}
}

func (x *ReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type GetAllReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReviewsResponse) Reset() {
	*x = GetAllReviewsResponse{}
	mi := &file_tour_proto_tour_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReviewsResponse) ProtoMessage() {}

func (x *GetAllReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_tour_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetAllReviewsResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_tour_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_tour_proto_tour_proto protoreflect.FileDescriptor

const file_tour_proto_tour_proto_rawDesc = "" +
	"\n" +
	"\x15tour/proto/tour.proto\x12\x04tour\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xc2\x01\n" +
	"\bKeypoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\"w\n" +
	"\vRouteOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12#\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x0f.tour.RouteModeR\x04mode\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\"\xb4\x04\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x01(\tR\x04tags\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.tour.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1a\n" +
	"\bdistance\x18\t \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x03R\bduration\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fpublished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12;\n" +
	"\varchived_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\x12,\n" +
	"\tkeypoints\x18\x0e \x03(\v2\x0e.tour.KeypointR\tkeypoints\x126\n" +
	"\rroute_options\x18\x0f \x03(\v2\x11.tour.RouteOptionR\frouteOptions\"\x93\x02\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"visited_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tvisitedAt\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\"3\n" +
	"\x11CreateTourRequest\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"3\n" +
	"\x11UpdateTourRequest\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\" \n" +
	"\x0eGetTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x15GetToursByUserRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"#\n" +
	"\x11DeleteTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x13CreateReviewRequest\x12$\n" +
	"\x06review\x18\x01 \x01(\v2\f.tour.ReviewR\x06review\"2\n" +
	"\x17GetReviewsByTourRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\"%\n" +
	"\x13DeleteReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\fTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"7\n" +
	"\x13GetAllToursResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\"6\n" +
	"\x0eReviewResponse\x12$\n" +
	"\x06review\x18\x01 \x01(\v2\f.tour.ReviewR\x06review\"?\n" +
	"\x15GetAllReviewsResponse\x12&\n" +
	"\areviews\x18\x01 \x03(\v2\f.tour.ReviewR\areviews*2\n" +
	"\tRouteMode\x12\v\n" +
	"\aWALKING\x10\x00\x12\v\n" +
	"\aCYCLING\x10\x01\x12\v\n" +
	"\aDRIVING\x10\x02*4\n" +
	"\n" +
	"TourStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x022\x99\a\n" +
	"\vTourService\x12N\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x12.tour.TourResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x04tour\"\x05/tour\x12G\n" +
	"\aGetTour\x12\x14.tour.GetTourRequest\x1a\x12.tour.TourResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/tour/{id}\x12P\n" +
	"\vGetAllTours\x12\x16.google.protobuf.Empty\x1a\x19.tour.GetAllToursResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/tours\x12l\n" +
	"\x0eGetToursByUser\x12\x1b.tour.GetToursByUserRequest\x1a\x19.tour.GetAllToursResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/tours/myTours/{user_name}\x12U\n" +
	"\n" +
	"UpdateTour\x12\x17.tour.UpdateTourRequest\x1a\x12.tour.TourResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x04tour2\f/tour/update\x12M\n" +
	"\n" +
	"DeleteTour\x12\x17.tour.DeleteTourRequest\x1a\x12.tour.TourResponse\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/tour/{id}\x12_\n" +
	"\fCreateReview\x12\x19.tour.CreateReviewRequest\x1a\x14.tour.ReviewResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x06review\"\x0e/review/create\x12n\n" +
	"\x10GetReviewsByTour\x12\x1d.tour.GetReviewsByTourRequest\x1a\x1b.tour.GetAllReviewsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/review/tour/{tour_id}\x12\\\n" +
	"\rGetAllReviews\x12\x16.google.protobuf.Empty\x1a\x1b.tour.GetAllReviewsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/review/getAll\x12\\\n" +
	"\fDeleteReview\x12\x19.tour.DeleteReviewRequest\x1a\x14.tour.ReviewResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/review/delete/{id}B\x1cZ\x1aPROJEKAT/COMMON/tour/protob\x06proto3"

var (
	file_tour_proto_tour_proto_rawDescOnce sync.Once
	file_tour_proto_tour_proto_rawDescData []byte
)

func file_tour_proto_tour_proto_rawDescGZIP() []byte {
	file_tour_proto_tour_proto_rawDescOnce.Do(func() {
		file_tour_proto_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_proto_tour_proto_rawDesc), len(file_tour_proto_tour_proto_rawDesc)))
	})
	return file_tour_proto_tour_proto_rawDescData
}

var file_tour_proto_tour_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tour_proto_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_tour_proto_tour_proto_goTypes = []any{
	(RouteMode)(0),                  // 0: tour.RouteMode
	(TourStatus)(0),                 // 1: tour.TourStatus
	(*Keypoint)(nil),                // 2: tour.Keypoint
	(*RouteOption)(nil),             // 3: tour.RouteOption
	(*Tour)(nil),                    // 4: tour.Tour
	(*Review)(nil),                  // 5: tour.Review
	(*CreateTourRequest)(nil),       // 6: tour.CreateTourRequest
	(*UpdateTourRequest)(nil),       // 7: tour.UpdateTourRequest
	(*GetTourRequest)(nil),          // 8: tour.GetTourRequest
	(*GetToursByUserRequest)(nil),   // 9: tour.GetToursByUserRequest
	(*DeleteTourRequest)(nil),       // 10: tour.DeleteTourRequest
	(*CreateReviewRequest)(nil),     // 11: tour.CreateReviewRequest
	(*GetReviewsByTourRequest)(nil), // 12: tour.GetReviewsByTourRequest
	(*DeleteReviewRequest)(nil),     // 13: tour.DeleteReviewRequest
	(*TourResponse)(nil),            // 14: tour.TourResponse
	(*GetAllToursResponse)(nil),     // 15: tour.GetAllToursResponse
	(*ReviewResponse)(nil),          // 16: tour.ReviewResponse
	(*GetAllReviewsResponse)(nil),   // 17: tour.GetAllReviewsResponse
	(*timestamppb.Timestamp)(nil),   // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 19: google.protobuf.Empty
}
var file_tour_proto_tour_proto_depIdxs = []int32{
	0,  // 0: tour.RouteOption.mode:type_name -> tour.RouteMode
	1,  // 1: tour.Tour.status:type_name -> tour.TourStatus
	18, // 2: tour.Tour.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: tour.Tour.published_at:type_name -> google.protobuf.Timestamp
	18, // 4: tour.Tour.archived_at:type_name -> google.protobuf.Timestamp
	2,  // 5: tour.Tour.keypoints:type_name -> tour.Keypoint
	3,  // 6: tour.Tour.route_options:type_name -> tour.RouteOption
	18, // 7: tour.Review.created_at:type_name -> google.protobuf.Timestamp
	18, // 8: tour.Review.visited_at:type_name -> google.protobuf.Timestamp
	4,  // 9: tour.CreateTourRequest.tour:type_name -> tour.Tour
	4,  // 10: tour.UpdateTourRequest.tour:type_name -> tour.Tour
	5,  // 11: tour.CreateReviewRequest.review:type_name -> tour.Review
	4,  // 12: tour.TourResponse.tour:type_name -> tour.Tour
	4,  // 13: tour.GetAllToursResponse.tours:type_name -> tour.Tour
	5,  // 14: tour.ReviewResponse.review:type_name -> tour.Review
	5,  // 15: tour.GetAllReviewsResponse.reviews:type_name -> tour.Review
	6,  // 16: tour.TourService.CreateTour:input_type -> tour.CreateTourRequest
	8,  // 17: tour.TourService.GetTour:input_type -> tour.GetTourRequest
	19, // 18: tour.TourService.GetAllTours:input_type -> google.protobuf.Empty
	9,  // 19: tour.TourService.GetToursByUser:input_type -> tour.GetToursByUserRequest
	7,  // 20: tour.TourService.UpdateTour:input_type -> tour.UpdateTourRequest
	10, // 21: tour.TourService.DeleteTour:input_type -> tour.DeleteTourRequest
	11, // 22: tour.TourService.CreateReview:input_type -> tour.CreateReviewRequest
	12, // 23: tour.TourService.GetReviewsByTour:input_type -> tour.GetReviewsByTourRequest
	19, // 24: tour.TourService.GetAllReviews:input_type -> google.protobuf.Empty
	13, // 25: tour.TourService.DeleteReview:input_type -> tour.DeleteReviewRequest
	14, // 26: tour.TourService.CreateTour:output_type -> tour.TourResponse
	14, // 27: tour.TourService.GetTour:output_type -> tour.TourResponse
	15, // 28: tour.TourService.GetAllTours:output_type -> tour.GetAllToursResponse
	15, // 29: tour.TourService.GetToursByUser:output_type -> tour.GetAllToursResponse
	14, // 30: tour.TourService.UpdateTour:output_type -> tour.TourResponse
	14, // 31: tour.TourService.DeleteTour:output_type -> tour.TourResponse
	16, // 32: tour.TourService.CreateReview:output_type -> tour.ReviewResponse
	17, // 33: tour.TourService.GetReviewsByTour:output_type -> tour.GetAllReviewsResponse
	17, // 34: tour.TourService.GetAllReviews:output_type -> tour.GetAllReviewsResponse
	16, // 35: tour.TourService.DeleteReview:output_type -> tour.ReviewResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_tour_proto_tour_proto_init() }
func file_tour_proto_tour_proto_init() {
	if File_tour_proto_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_proto_tour_proto_rawDesc), len(file_tour_proto_tour_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_proto_tour_proto_goTypes,
		DependencyIndexes: file_tour_proto_tour_proto_depIdxs,
		EnumInfos:         file_tour_proto_tour_proto_enumTypes,
		MessageInfos:      file_tour_proto_tour_proto_msgTypes,
	}.Build()
	File_tour_proto_tour_proto = out.File
	file_tour_proto_tour_proto_goTypes = nil
	file_tour_proto_tour_proto_depIdxs = nil
}
