// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: tour/proto/tour.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourService_CreateTour_FullMethodName                 = "/tour.TourService/CreateTour"
	TourService_GetTour_FullMethodName                    = "/tour.TourService/GetTour"
	TourService_GetAllTours_FullMethodName                = "/tour.TourService/GetAllTours"
	TourService_GetToursByUser_FullMethodName             = "/tour.TourService/GetToursByUser"
	TourService_UpdateTour_FullMethodName                 = "/tour.TourService/UpdateTour"
	TourService_DeleteTour_FullMethodName                 = "/tour.TourService/DeleteTour"
	TourService_CreateReview_FullMethodName               = "/tour.TourService/CreateReview"
	TourService_GetReviewsByTour_FullMethodName           = "/tour.TourService/GetReviewsByTour"
	TourService_GetAllReviews_FullMethodName              = "/tour.TourService/GetAllReviews"
	TourService_DeleteReview_FullMethodName               = "/tour.TourService/DeleteReview"
	TourService_ActivateTour_FullMethodName               = "/tour.TourService/ActivateTour"
	TourService_GetTourExecutionByTourUser_FullMethodName = "/tour.TourService/GetTourExecutionByTourUser"
	TourService_AbandonTourExecution_FullMethodName       = "/tour.TourService/AbandonTourExecution"
	TourService_SetCurrentLocation_FullMethodName         = "/tour.TourService/SetCurrentLocation"
	TourService_CheckCloseKeyPoints_FullMethodName        = "/tour.TourService/CheckCloseKeyPoints"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =========================
// SERVICE WITH ANNOTATIONS
// =========================
type TourServiceClient interface {
	// Tours
	CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*TourResponse, error)
	GetTour(ctx context.Context, in *GetTourRequest, opts ...grpc.CallOption) (*TourResponse, error)
	GetAllTours(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllToursResponse, error)
	GetToursByUser(ctx context.Context, in *GetToursByUserRequest, opts ...grpc.CallOption) (*GetAllToursResponse, error)
	UpdateTour(ctx context.Context, in *UpdateTourRequest, opts ...grpc.CallOption) (*TourResponse, error)
	DeleteTour(ctx context.Context, in *DeleteTourRequest, opts ...grpc.CallOption) (*TourResponse, error)
	// Reviews
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
	GetReviewsByTour(ctx context.Context, in *GetReviewsByTourRequest, opts ...grpc.CallOption) (*GetAllReviewsResponse, error)
	GetAllReviews(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllReviewsResponse, error)
	DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
	ActivateTour(ctx context.Context, in *ActivateTourRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
	GetTourExecutionByTourUser(ctx context.Context, in *TourExecutionByTourUserRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
	AbandonTourExecution(ctx context.Context, in *AbandonTourExecutionRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
	SetCurrentLocation(ctx context.Context, in *SetCurrentLocationRequest, opts ...grpc.CallOption) (*SetCurrentLocationResponse, error)
	CheckCloseKeyPoints(ctx context.Context, in *CheckCloseKeyPointsRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, TourService_CreateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTour(ctx context.Context, in *GetTourRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, TourService_GetTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetAllTours(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllToursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllToursResponse)
	err := c.cc.Invoke(ctx, TourService_GetAllTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetToursByUser(ctx context.Context, in *GetToursByUserRequest, opts ...grpc.CallOption) (*GetAllToursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllToursResponse)
	err := c.cc.Invoke(ctx, TourService_GetToursByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) UpdateTour(ctx context.Context, in *UpdateTourRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, TourService_UpdateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) DeleteTour(ctx context.Context, in *DeleteTourRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, TourService_DeleteTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, TourService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetReviewsByTour(ctx context.Context, in *GetReviewsByTourRequest, opts ...grpc.CallOption) (*GetAllReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllReviewsResponse)
	err := c.cc.Invoke(ctx, TourService_GetReviewsByTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetAllReviews(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllReviewsResponse)
	err := c.cc.Invoke(ctx, TourService_GetAllReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, TourService_DeleteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) ActivateTour(ctx context.Context, in *ActivateTourRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_ActivateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTourExecutionByTourUser(ctx context.Context, in *TourExecutionByTourUserRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_GetTourExecutionByTourUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) AbandonTourExecution(ctx context.Context, in *AbandonTourExecutionRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_AbandonTourExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) SetCurrentLocation(ctx context.Context, in *SetCurrentLocationRequest, opts ...grpc.CallOption) (*SetCurrentLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCurrentLocationResponse)
	err := c.cc.Invoke(ctx, TourService_SetCurrentLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CheckCloseKeyPoints(ctx context.Context, in *CheckCloseKeyPointsRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_CheckCloseKeyPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility.
//
// =========================
// SERVICE WITH ANNOTATIONS
// =========================
type TourServiceServer interface {
	// Tours
	CreateTour(context.Context, *CreateTourRequest) (*TourResponse, error)
	GetTour(context.Context, *GetTourRequest) (*TourResponse, error)
	GetAllTours(context.Context, *emptypb.Empty) (*GetAllToursResponse, error)
	GetToursByUser(context.Context, *GetToursByUserRequest) (*GetAllToursResponse, error)
	UpdateTour(context.Context, *UpdateTourRequest) (*TourResponse, error)
	DeleteTour(context.Context, *DeleteTourRequest) (*TourResponse, error)
	// Reviews
	CreateReview(context.Context, *CreateReviewRequest) (*ReviewResponse, error)
	GetReviewsByTour(context.Context, *GetReviewsByTourRequest) (*GetAllReviewsResponse, error)
	GetAllReviews(context.Context, *emptypb.Empty) (*GetAllReviewsResponse, error)
	DeleteReview(context.Context, *DeleteReviewRequest) (*ReviewResponse, error)
	ActivateTour(context.Context, *ActivateTourRequest) (*TourExecutionResponse, error)
	GetTourExecutionByTourUser(context.Context, *TourExecutionByTourUserRequest) (*TourExecutionResponse, error)
	AbandonTourExecution(context.Context, *AbandonTourExecutionRequest) (*TourExecutionResponse, error)
	SetCurrentLocation(context.Context, *SetCurrentLocationRequest) (*SetCurrentLocationResponse, error)
	CheckCloseKeyPoints(context.Context, *CheckCloseKeyPointsRequest) (*TourExecutionResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourServiceServer struct{}

func (UnimplementedTourServiceServer) CreateTour(context.Context, *CreateTourRequest) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourServiceServer) GetTour(context.Context, *GetTourRequest) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTour not implemented")
}
func (UnimplementedTourServiceServer) GetAllTours(context.Context, *emptypb.Empty) (*GetAllToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTours not implemented")
}
func (UnimplementedTourServiceServer) GetToursByUser(context.Context, *GetToursByUserRequest) (*GetAllToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToursByUser not implemented")
}
func (UnimplementedTourServiceServer) UpdateTour(context.Context, *UpdateTourRequest) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTour not implemented")
}
func (UnimplementedTourServiceServer) DeleteTour(context.Context, *DeleteTourRequest) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTour not implemented")
}
func (UnimplementedTourServiceServer) CreateReview(context.Context, *CreateReviewRequest) (*ReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedTourServiceServer) GetReviewsByTour(context.Context, *GetReviewsByTourRequest) (*GetAllReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewsByTour not implemented")
}
func (UnimplementedTourServiceServer) GetAllReviews(context.Context, *emptypb.Empty) (*GetAllReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllReviews not implemented")
}
func (UnimplementedTourServiceServer) DeleteReview(context.Context, *DeleteReviewRequest) (*ReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedTourServiceServer) ActivateTour(context.Context, *ActivateTourRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateTour not implemented")
}
func (UnimplementedTourServiceServer) GetTourExecutionByTourUser(context.Context, *TourExecutionByTourUserRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourExecutionByTourUser not implemented")
}
func (UnimplementedTourServiceServer) AbandonTourExecution(context.Context, *AbandonTourExecutionRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonTourExecution not implemented")
}
func (UnimplementedTourServiceServer) SetCurrentLocation(context.Context, *SetCurrentLocationRequest) (*SetCurrentLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCurrentLocation not implemented")
}
func (UnimplementedTourServiceServer) CheckCloseKeyPoints(context.Context, *CheckCloseKeyPointsRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCloseKeyPoints not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}
func (UnimplementedTourServiceServer) testEmbeddedByValue()                     {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	// If the following call pancis, it indicates UnimplementedTourServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateTour(ctx, req.(*CreateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTour(ctx, req.(*GetTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetAllTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetAllTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetAllTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetAllTours(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetToursByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToursByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetToursByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetToursByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetToursByUser(ctx, req.(*GetToursByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_UpdateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).UpdateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_UpdateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).UpdateTour(ctx, req.(*UpdateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_DeleteTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).DeleteTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_DeleteTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).DeleteTour(ctx, req.(*DeleteTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetReviewsByTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewsByTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetReviewsByTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetReviewsByTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetReviewsByTour(ctx, req.(*GetReviewsByTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetAllReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetAllReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetAllReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetAllReviews(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_DeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).DeleteReview(ctx, req.(*DeleteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_ActivateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).ActivateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_ActivateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).ActivateTour(ctx, req.(*ActivateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTourExecutionByTourUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourExecutionByTourUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourExecutionByTourUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTourExecutionByTourUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourExecutionByTourUser(ctx, req.(*TourExecutionByTourUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_AbandonTourExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonTourExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).AbandonTourExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_AbandonTourExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).AbandonTourExecution(ctx, req.(*AbandonTourExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_SetCurrentLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCurrentLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).SetCurrentLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_SetCurrentLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).SetCurrentLocation(ctx, req.(*SetCurrentLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CheckCloseKeyPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCloseKeyPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CheckCloseKeyPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CheckCloseKeyPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CheckCloseKeyPoints(ctx, req.(*CheckCloseKeyPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTour",
			Handler:    _TourService_CreateTour_Handler,
		},
		{
			MethodName: "GetTour",
			Handler:    _TourService_GetTour_Handler,
		},
		{
			MethodName: "GetAllTours",
			Handler:    _TourService_GetAllTours_Handler,
		},
		{
			MethodName: "GetToursByUser",
			Handler:    _TourService_GetToursByUser_Handler,
		},
		{
			MethodName: "UpdateTour",
			Handler:    _TourService_UpdateTour_Handler,
		},
		{
			MethodName: "DeleteTour",
			Handler:    _TourService_DeleteTour_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _TourService_CreateReview_Handler,
		},
		{
			MethodName: "GetReviewsByTour",
			Handler:    _TourService_GetReviewsByTour_Handler,
		},
		{
			MethodName: "GetAllReviews",
			Handler:    _TourService_GetAllReviews_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _TourService_DeleteReview_Handler,
		},
		{
			MethodName: "ActivateTour",
			Handler:    _TourService_ActivateTour_Handler,
		},
		{
			MethodName: "GetTourExecutionByTourUser",
			Handler:    _TourService_GetTourExecutionByTourUser_Handler,
		},
		{
			MethodName: "AbandonTourExecution",
			Handler:    _TourService_AbandonTourExecution_Handler,
		},
		{
			MethodName: "SetCurrentLocation",
			Handler:    _TourService_SetCurrentLocation_Handler,
		},
		{
			MethodName: "CheckCloseKeyPoints",
			Handler:    _TourService_CheckCloseKeyPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour/proto/tour.proto",
}
