// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: blog/proto/blog.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImagePaths    []string               `protobuf:"bytes,4,rep,name=image_paths,json=imagePaths,proto3" json:"image_paths,omitempty"`
	LikeCount     int32                  `protobuf:"varint,5,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_blog_proto_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{0}
}

func (x *PostResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostResponse) GetImagePaths() []string {
	if x != nil {
		return x.ImagePaths
	}
	return nil
}

func (x *PostResponse) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_blog_proto_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CommentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CommentResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *CommentResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CommentResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommentResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetAllPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostResponse        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsResponse) Reset() {
	*x = GetAllPostsResponse{}
	mi := &file_blog_proto_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsResponse) ProtoMessage() {}

func (x *GetAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllPostsResponse) GetPosts() []*PostResponse {
	if x != nil {
		return x.Posts
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImagePaths    []string               `protobuf:"bytes,3,rep,name=image_paths,json=imagePaths,proto3" json:"image_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_blog_proto_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePostRequest) GetImagePaths() []string {
	if x != nil {
		return x.ImagePaths
	}
	return nil
}

type ToggleLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeRequest) Reset() {
	*x = ToggleLikeRequest{}
	mi := &file_blog_proto_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeRequest) ProtoMessage() {}

func (x *ToggleLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeRequest.ProtoReflect.Descriptor instead.
func (*ToggleLikeRequest) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{4}
}

func (x *ToggleLikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_blog_proto_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommentsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentResponse     `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_blog_proto_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommentsResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"` // AuthorId and AuthorName will be extracted from JWT in C# code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_blog_proto_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_blog_proto_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UpdateCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_blog_proto_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_blog_proto_blog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_blog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_blog_proto_blog_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_blog_proto_blog_proto protoreflect.FileDescriptor

const file_blog_proto_blog_proto_rawDesc = "" +
	"\n" +
	"\x15blog/proto/blog.proto\x12\x04blog\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x01\n" +
	"\fPostResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vimage_paths\x18\x04 \x03(\tR\n" +
	"imagePaths\x12\x1d\n" +
	"\n" +
	"like_count\x18\x05 \x01(\x05R\tlikeCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x02\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x13GetAllPostsResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\x12.blog.PostResponseR\x05posts\"l\n" +
	"\x11CreatePostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vimage_paths\x18\x03 \x03(\tR\n" +
	"imagePaths\",\n" +
	"\x11ToggleLikeRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"-\n" +
	"\x12GetCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"H\n" +
	"\x13GetCommentsResponse\x121\n" +
	"\bcomments\x18\x01 \x03(\v2\x15.blog.CommentResponseR\bcomments\"C\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"I\n" +
	"\x14UpdateCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xdb\x05\n" +
	"\vBlogService\x12Y\n" +
	"\vGetAllPosts\x12\x16.google.protobuf.Empty\x1a\x19.blog.GetAllPostsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/blog/posts\x12U\n" +
	"\n" +
	"CreatePost\x12\x17.blog.CreatePostRequest\x1a\x12.blog.PostResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/blog/posts\x12d\n" +
	"\n" +
	"ToggleLike\x12\x17.blog.ToggleLikeRequest\x1a\x12.blog.PostResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/blog/posts/{post_id}/like\x12n\n" +
	"\vGetComments\x12\x18.blog.GetCommentsRequest\x1a\x19.blog.GetCommentsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/blog/posts/{post_id}/comments\x12a\n" +
	"\rCreateComment\x12\x1a.blog.CreateCommentRequest\x1a\x15.blog.CommentResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/blog/comments\x12n\n" +
	"\rUpdateComment\x12\x1a.blog.UpdateCommentRequest\x1a\x15.blog.CommentResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/blog/comments/{comment_id}\x12q\n" +
	"\rDeleteComment\x12\x1a.blog.DeleteCommentRequest\x1a\x1b.blog.DeleteCommentResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/api/blog/comments/{comment_id}B#Z\x1aPROJEKAT/COMMON/blog/proto\xaa\x02\x04Blogb\x06proto3"

var (
	file_blog_proto_blog_proto_rawDescOnce sync.Once
	file_blog_proto_blog_proto_rawDescData []byte
)

func file_blog_proto_blog_proto_rawDescGZIP() []byte {
	file_blog_proto_blog_proto_rawDescOnce.Do(func() {
		file_blog_proto_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_proto_blog_proto_rawDesc), len(file_blog_proto_blog_proto_rawDesc)))
	})
	return file_blog_proto_blog_proto_rawDescData
}

var file_blog_proto_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_blog_proto_blog_proto_goTypes = []any{
	(*PostResponse)(nil),          // 0: blog.PostResponse
	(*CommentResponse)(nil),       // 1: blog.CommentResponse
	(*GetAllPostsResponse)(nil),   // 2: blog.GetAllPostsResponse
	(*CreatePostRequest)(nil),     // 3: blog.CreatePostRequest
	(*ToggleLikeRequest)(nil),     // 4: blog.ToggleLikeRequest
	(*GetCommentsRequest)(nil),    // 5: blog.GetCommentsRequest
	(*GetCommentsResponse)(nil),   // 6: blog.GetCommentsResponse
	(*CreateCommentRequest)(nil),  // 7: blog.CreateCommentRequest
	(*UpdateCommentRequest)(nil),  // 8: blog.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),  // 9: blog.DeleteCommentRequest
	(*DeleteCommentResponse)(nil), // 10: blog.DeleteCommentResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_blog_proto_blog_proto_depIdxs = []int32{
	11, // 0: blog.PostResponse.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: blog.CommentResponse.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: blog.CommentResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: blog.GetAllPostsResponse.posts:type_name -> blog.PostResponse
	1,  // 4: blog.GetCommentsResponse.comments:type_name -> blog.CommentResponse
	12, // 5: blog.BlogService.GetAllPosts:input_type -> google.protobuf.Empty
	3,  // 6: blog.BlogService.CreatePost:input_type -> blog.CreatePostRequest
	4,  // 7: blog.BlogService.ToggleLike:input_type -> blog.ToggleLikeRequest
	5,  // 8: blog.BlogService.GetComments:input_type -> blog.GetCommentsRequest
	7,  // 9: blog.BlogService.CreateComment:input_type -> blog.CreateCommentRequest
	8,  // 10: blog.BlogService.UpdateComment:input_type -> blog.UpdateCommentRequest
	9,  // 11: blog.BlogService.DeleteComment:input_type -> blog.DeleteCommentRequest
	2,  // 12: blog.BlogService.GetAllPosts:output_type -> blog.GetAllPostsResponse
	0,  // 13: blog.BlogService.CreatePost:output_type -> blog.PostResponse
	0,  // 14: blog.BlogService.ToggleLike:output_type -> blog.PostResponse
	6,  // 15: blog.BlogService.GetComments:output_type -> blog.GetCommentsResponse
	1,  // 16: blog.BlogService.CreateComment:output_type -> blog.CommentResponse
	1,  // 17: blog.BlogService.UpdateComment:output_type -> blog.CommentResponse
	10, // 18: blog.BlogService.DeleteComment:output_type -> blog.DeleteCommentResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_blog_proto_blog_proto_init() }
func file_blog_proto_blog_proto_init() {
	if File_blog_proto_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_proto_blog_proto_rawDesc), len(file_blog_proto_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_proto_blog_proto_goTypes,
		DependencyIndexes: file_blog_proto_blog_proto_depIdxs,
		MessageInfos:      file_blog_proto_blog_proto_msgTypes,
	}.Build()
	File_blog_proto_blog_proto = out.File
	file_blog_proto_blog_proto_goTypes = nil
	file_blog_proto_blog_proto_depIdxs = nil
}
