syntax = "proto3";

package tour;

option go_package = "PROJEKAT/COMMON/tour/proto";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

enum RouteMode {
  WALKING = 0;
  CYCLING = 1;
  DRIVING = 2;
}

message RouteOption {
  string id = 1;
  string tour_id = 2;
  RouteMode mode = 3;
  int64 duration_ms = 4; // time.Duration in milliseconds
}

message Keypoint {
  string id = 1;
  string tour_id = 2;
  string title = 3;
  double latitude = 4;
  double longitude = 5;
  string description = 6;
  string image_url = 7;
}

message Tour {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string description = 4;
  string difficulty = 5;
  string tags = 6;
  string status = 7;
  double price = 8;
  double distance = 9;
  int64 duration_ms = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp published_at = 12;
  google.protobuf.Timestamp archived_at = 13;
  repeated Keypoint keypoints = 14;
  repeated RouteOption route_options = 15;
}

message Review {
  string id = 1;
  string tour_id = 2;
  string user_id = 3;
  string user_name = 4;
  int32 rating = 5;
  string comment = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp visited_at = 8;
  string image_url = 9;
}

// Requests
message CreateTourRequest {
  string user_id = 1;
  string title = 2;
  string description = 3;
  string difficulty = 4;
  string tags = 5;
  double price = 6;
  double distance = 7;
  int64 duration_ms = 8;
  repeated Keypoint keypoints = 9;
  repeated RouteOption route_options = 10;
}

message UpdateTourRequest {
  string id = 1;
  string title = 2;
  string description = 3;
  string difficulty = 4;
  string tags = 5;
  string status = 6;
  double price = 7;
  double distance = 8;
  int64 duration_ms = 9;
  repeated Keypoint keypoints = 10;
  repeated RouteOption route_options = 11;
}

message GetTourRequest {
  string id = 1;
}

message GetToursByUserRequest {
  string user_id = 1;
}

message CreateReviewRequest {
  string tour_id = 1;
  string user_id = 2;
  string user_name = 3;
  int32 rating = 4;
  string comment = 5;
  google.protobuf.Timestamp visited_at = 6;
  string image_url = 7;
}

message GetReviewsByTourRequest {
  string tour_id = 1;
}

message DeleteTourRequest {
  string id = 1;
}

message DeleteReviewRequest {
  string id = 1;
}

// Responses
message TourResponse {
  Tour tour = 1;
}

message GetAllToursResponse {
  repeated Tour tours = 1;
}

message ReviewResponse {
  Review review = 1;
}

message GetAllReviewsResponse {
  repeated Review reviews = 1;
}

// -------------------- Service --------------------
service TourService {
  rpc CreateTour(CreateTourRequest) returns (TourResponse) {
    option (google.api.http) = {
      post: "/tour"
      body: "*"
    };
  }

  rpc GetTour(GetTourRequest) returns (TourResponse) {
    option (google.api.http) = {
      get: "/tour/{id}"
    };
  }

  rpc GetAllTours(google.protobuf.Empty) returns (GetAllToursResponse) {
    option (google.api.http) = {
      get: "/tours"
    };
  }

  rpc DeleteTour(DeleteTourRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/tour/{id}"
    };
  }

  rpc UpdateTour(UpdateTourRequest) returns (TourResponse) {
    option (google.api.http) = {
      patch: "/tour/update"
      body: "*"
    };
  }

  rpc GetToursByUser(GetToursByUserRequest) returns (GetAllToursResponse) {
    option (google.api.http) = {
      get: "/tours/myTours/{user_id}"
    };
  }

  rpc CreateReview(CreateReviewRequest) returns (ReviewResponse) {
    option (google.api.http) = {
      post: "/review/create"
      body: "*"
    };
  }

  rpc GetReviewsByTour(GetReviewsByTourRequest) returns (GetAllReviewsResponse) {
    option (google.api.http) = {
      get: "/review/tour/{tour_id}"
    };
  }

  rpc DeleteReview(DeleteReviewRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/review/delete/{id}"
    };
  }

  rpc GetAllReviews(google.protobuf.Empty) returns (GetAllReviewsResponse) {
    option (google.api.http) = {
      get: "/review/getAll"
    };
  }
}
