// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: shopping-cart/proto/shopping-cart.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *CartItem) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *CartItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddItemRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveItemRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{5}
}

func (x *CheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PurchaseToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseToken) Reset() {
	*x = PurchaseToken{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseToken) ProtoMessage() {}

func (x *PurchaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseToken.ProtoReflect.Descriptor instead.
func (*PurchaseToken) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{6}
}

func (x *PurchaseToken) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *PurchaseToken) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PurchaseToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Tokens        []*PurchaseToken       `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CheckoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckoutResponse) GetTokens() []*PurchaseToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type PurchaseCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseCheckRequest) Reset() {
	*x = PurchaseCheckRequest{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseCheckRequest) ProtoMessage() {}

func (x *PurchaseCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseCheckRequest.ProtoReflect.Descriptor instead.
func (*PurchaseCheckRequest) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{8}
}

func (x *PurchaseCheckRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PurchaseCheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PurchaseCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourPurchased bool                   `protobuf:"varint,1,opt,name=tour_purchased,json=tourPurchased,proto3" json:"tour_purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseCheckResponse) Reset() {
	*x = PurchaseCheckResponse{}
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseCheckResponse) ProtoMessage() {}

func (x *PurchaseCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_cart_proto_shopping_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseCheckResponse.ProtoReflect.Descriptor instead.
func (*PurchaseCheckResponse) Descriptor() ([]byte, []int) {
	return file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP(), []int{9}
}

func (x *PurchaseCheckResponse) GetTourPurchased() bool {
	if x != nil {
		return x.TourPurchased
	}
	return false
}

var File_shopping_cart_proto_shopping_cart_proto protoreflect.FileDescriptor

const file_shopping_cart_proto_shopping_cart_proto_rawDesc = "" +
	"\n" +
	"'shopping-cart/proto/shopping-cart.proto\x12\rshopping_cart\x1a\x1cgoogle/api/annotations.proto\"V\n" +
	"\bCartItem\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"w\n" +
	"\fCartResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.shopping_cart.CartItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"E\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"*\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\\\n" +
	"\rPurchaseToken\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"b\n" +
	"\x10CheckoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\x06tokens\x18\x02 \x03(\v2\x1c.shopping_cart.PurchaseTokenR\x06tokens\"H\n" +
	"\x14PurchaseCheckRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\">\n" +
	"\x15PurchaseCheckResponse\x12%\n" +
	"\x0etour_purchased\x18\x01 \x01(\bR\rtourPurchased2\xc7\x04\n" +
	"\x13ShoppingCartService\x12k\n" +
	"\aGetCart\x12\x1d.shopping_cart.GetCartRequest\x1a\x1b.shopping_cart.CartResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/shopping-cart/{user_id}\x12j\n" +
	"\aAddItem\x12\x1d.shopping_cart.AddItemRequest\x1a\x1b.shopping_cart.CartResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/shopping-cart/items\x12\x81\x01\n" +
	"\n" +
	"RemoveItem\x12 .shopping_cart.RemoveItemRequest\x1a\x1b.shopping_cart.CartResponse\"4\x82\xd3\xe4\x93\x02.*,/api/shopping-cart/items/{user_id}/{tour_id}\x12s\n" +
	"\bCheckout\x12\x1e.shopping_cart.CheckoutRequest\x1a\x1f.shopping_cart.CheckoutResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/shopping-cart/checkout\x12^\n" +
	"\x0fIsTourPurchased\x12#.shopping_cart.PurchaseCheckRequest\x1a$.shopping_cart.PurchaseCheckResponse\"\x00B%Z#PROJEKAT/COMMON/shopping-cart/protob\x06proto3"

var (
	file_shopping_cart_proto_shopping_cart_proto_rawDescOnce sync.Once
	file_shopping_cart_proto_shopping_cart_proto_rawDescData []byte
)

func file_shopping_cart_proto_shopping_cart_proto_rawDescGZIP() []byte {
	file_shopping_cart_proto_shopping_cart_proto_rawDescOnce.Do(func() {
		file_shopping_cart_proto_shopping_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopping_cart_proto_shopping_cart_proto_rawDesc), len(file_shopping_cart_proto_shopping_cart_proto_rawDesc)))
	})
	return file_shopping_cart_proto_shopping_cart_proto_rawDescData
}

var file_shopping_cart_proto_shopping_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shopping_cart_proto_shopping_cart_proto_goTypes = []any{
	(*CartItem)(nil),              // 0: shopping_cart.CartItem
	(*CartResponse)(nil),          // 1: shopping_cart.CartResponse
	(*GetCartRequest)(nil),        // 2: shopping_cart.GetCartRequest
	(*AddItemRequest)(nil),        // 3: shopping_cart.AddItemRequest
	(*RemoveItemRequest)(nil),     // 4: shopping_cart.RemoveItemRequest
	(*CheckoutRequest)(nil),       // 5: shopping_cart.CheckoutRequest
	(*PurchaseToken)(nil),         // 6: shopping_cart.PurchaseToken
	(*CheckoutResponse)(nil),      // 7: shopping_cart.CheckoutResponse
	(*PurchaseCheckRequest)(nil),  // 8: shopping_cart.PurchaseCheckRequest
	(*PurchaseCheckResponse)(nil), // 9: shopping_cart.PurchaseCheckResponse
}
var file_shopping_cart_proto_shopping_cart_proto_depIdxs = []int32{
	0, // 0: shopping_cart.CartResponse.items:type_name -> shopping_cart.CartItem
	6, // 1: shopping_cart.CheckoutResponse.tokens:type_name -> shopping_cart.PurchaseToken
	2, // 2: shopping_cart.ShoppingCartService.GetCart:input_type -> shopping_cart.GetCartRequest
	3, // 3: shopping_cart.ShoppingCartService.AddItem:input_type -> shopping_cart.AddItemRequest
	4, // 4: shopping_cart.ShoppingCartService.RemoveItem:input_type -> shopping_cart.RemoveItemRequest
	5, // 5: shopping_cart.ShoppingCartService.Checkout:input_type -> shopping_cart.CheckoutRequest
	8, // 6: shopping_cart.ShoppingCartService.IsTourPurchased:input_type -> shopping_cart.PurchaseCheckRequest
	1, // 7: shopping_cart.ShoppingCartService.GetCart:output_type -> shopping_cart.CartResponse
	1, // 8: shopping_cart.ShoppingCartService.AddItem:output_type -> shopping_cart.CartResponse
	1, // 9: shopping_cart.ShoppingCartService.RemoveItem:output_type -> shopping_cart.CartResponse
	7, // 10: shopping_cart.ShoppingCartService.Checkout:output_type -> shopping_cart.CheckoutResponse
	9, // 11: shopping_cart.ShoppingCartService.IsTourPurchased:output_type -> shopping_cart.PurchaseCheckResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shopping_cart_proto_shopping_cart_proto_init() }
func file_shopping_cart_proto_shopping_cart_proto_init() {
	if File_shopping_cart_proto_shopping_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopping_cart_proto_shopping_cart_proto_rawDesc), len(file_shopping_cart_proto_shopping_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopping_cart_proto_shopping_cart_proto_goTypes,
		DependencyIndexes: file_shopping_cart_proto_shopping_cart_proto_depIdxs,
		MessageInfos:      file_shopping_cart_proto_shopping_cart_proto_msgTypes,
	}.Build()
	File_shopping_cart_proto_shopping_cart_proto = out.File
	file_shopping_cart_proto_shopping_cart_proto_goTypes = nil
	file_shopping_cart_proto_shopping_cart_proto_depIdxs = nil
}
